name = "MultivariateSeries"
repo = "https://github.com/JuliaAlgebra/MultivariateSeries.jl.git"
version = "0.0.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"

[compat]
MultivariatePolynomials = "≥ 0.1.0"
julia = "1"
