name = "MultivariateSeries"
uuid = "08acae6c-c1bf-11e9-0c27-6b1945f8789b"
authors = ["mourrain <bernard.mourrain@inria.fr>"]
repo = "https://github.com/bmourrain/MultivariateSeries.jl.git"
version = "0.1.3"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DynamicPolynomials = "7c1d4256-1411-5781-91ec-d7bc3513ac07"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MultivariatePolynomials = "102ac46a-7ee4-5c85-9060-abc95bfdeaa3"

[compat]
DataStructures = "0.17, 0.18"
DynamicPolynomials = "0.3"
MultivariatePolynomials = "0.3"
julia = "1"
